name: Trigger workflow run and wait

inputs:
  owner:
    description: 'Owner of the repository containing the workflow.'
    required: true
  repo:
    description: 'Repository containing the workflow.'
    required: true
  workflow:
    description: 'Name of the workflow which should be triggered.'
    required: true
  token:
    description: 'Github access token with access to the repository.'
    required: true
  ref:
    description: 'The reference of the workflow run.'
    required: true
  owgw_version:
    description: 'OpenWIFI Gateway version to be deployed.'
    required: false
  owgwui_version:
    description: 'OpenWIFI Web UI version to be deployed.'
    required: false
  owsec_version:
    description: 'OpenWIFI Security version to be deployed.'
    required: false
  owfms_version:
    description: 'OpenWIFI Firmware version to be deployed.'
    required: false
  owprov_version:
    description: 'OpenWIFI Provisioning version to be deployed.'
    required: false
  owprovui_version:
    description: 'OpenWIFI Provisioning Web UI version to be deployed.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Execute Python script to trigger workflow run
      shell: bash
      run: |
        python ${{ github.action_path }}/github_action_dispatch_runid.py --owner ${{ inputs.owner }} --repo ${{ inputs.repo }} --workflow ${{ inputs.workflow }} --token ${{ inputs.token }} --ref ${{ inputs.ref }} --owgw_version ${{ inputs.owgw_version || 'master' }} --owgwui_version ${{ inputs.owgwui_version || 'main' }} --owsec_version ${{ inputs.owsec_version || 'main' }} --owfms_version ${{ inputs.owfms_version || 'main' }} --owprov_version ${{ inputs.owprov_version || 'main' }} --owprovui_version ${{ inputs.owprovui_version || 'main' }}
