name: Build and push microservice Docker image
description: Build image using BuildKit and Github cache

inputs:
  image_name:
    description: Name of the image you want to build
    required: true
  registry:
    description: the registry to push to
    required: true
  registry_user:
    description: the user to authenticate against the registry
    required: true
  registry_password:
    description: the password to authenticate against the registry
    required: true
  checkout_fetch_depth:
    description: sets "fetch-depth" in "actions/checkout"
    default: 1

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: ${{ inputs.checkout_fetch_depth }}
      path: docker-image-build

  - name: Set up Docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@v3
    with:
      install: true

  - name: Log into Docker registry
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.registry_user }}
      password: ${{ inputs.registry_password }}

  - name: Set branch name output
    shell: bash
    id: set_branch_name
    run: |
      if [[ ${GITHUB_REF} == "refs/heads/"* ]]
      then
        echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_OUTPUT
      else
        if [[ ${GITHUB_REF} == "refs/tags/"* ]]
        then
          echo "branch_name=$(echo ${GITHUB_REF#refs/tags/} | tr '/' '-')" >> $GITHUB_OUTPUT
        else # PR build
          echo "branch_name=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_OUTPUT
        fi
      fi

  - name: Build and push
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    uses: docker/build-push-action@v6
    env:
      BRANCH_NAME: ${{ steps.set_branch_name.outputs.branch_name }}
    with:
      context: ./docker-image-build
      push: true
      tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.sha }},${{ inputs.registry }}/${{ inputs.image_name }}:${{ env.BRANCH_NAME }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
